//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Admin_Page = new HashSet<Admin_Page>();
        }
    
        public System.Guid Admin_Id { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public short Unit_Id { get; set; }
        public Nullable<short> Title_Id { get; set; }
        public Nullable<short> Organization_Id { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string email { get; set; }
        public string Fax { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<Admin_Page> Admin_Page { get; set; }
    }
}
