//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aerc_System
    {
        public Aerc_System()
        {
            this.Funtion_Group = new HashSet<Funtion_Group>();
        }
    
        public short System_Id { get; set; }
        public string System { get; set; }
        public Nullable<bool> Staus { get; set; }
    
        public virtual ICollection<Funtion_Group> Funtion_Group { get; set; }
    }
}
