//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City_Area
    {
        public City_Area()
        {
            this.City = new HashSet<City>();
        }
    
        public byte City_Area_Id { get; set; }
        public string Area_Place { get; set; }
    
        public virtual ICollection<City> City { get; set; }
    }
}
