//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommonEntities : DbContext
    {
        public CommonEntities()
            : base("name=CommonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin_Page> Admin_Page { get; set; }
        public DbSet<Aerc_System> Aerc_System { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<City_Area> City_Area { get; set; }
        public DbSet<Crop> Crop { get; set; }
        public DbSet<Crop_Type> Crop_Type { get; set; }
        public DbSet<Function_Page> Function_Page { get; set; }
        public DbSet<Funtion_Group> Funtion_Group { get; set; }
        public DbSet<Land_Number> Land_Number { get; set; }
        public DbSet<Land_Office> Land_Office { get; set; }
        public DbSet<Land_Type> Land_Type { get; set; }
        public DbSet<Organization> Organization { get; set; }
        public DbSet<Section> Section { get; set; }
        public DbSet<Soil> Soil { get; set; }
        public DbSet<Soil_Type> Soil_Type { get; set; }
        public DbSet<Structure> Structure { get; set; }
        public DbSet<StructureKind> StructureKind { get; set; }
        public DbSet<StructureType> StructureType { get; set; }
        public DbSet<Title> Title { get; set; }
        public DbSet<Title_Page> Title_Page { get; set; }
        public DbSet<Unit> Unit { get; set; }
        public DbSet<Unit_Town> Unit_Town { get; set; }
        public DbSet<AdminQuery> AdminQuery { get; set; }
        public DbSet<View_Admin> View_Admin { get; set; }
        public DbSet<Town> Town { get; set; }
        public DbSet<Admin> Admin { get; set; }
    }
}
