//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function_Page
    {
        public Function_Page()
        {
            this.Title_Page = new HashSet<Title_Page>();
        }
    
        public short Funtion_Page_Id { get; set; }
        public string Funtion_Page { get; set; }
        public Nullable<short> Funtion_Group_Id { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Funtion_Group Funtion_Group { get; set; }
        public virtual ICollection<Title_Page> Title_Page { get; set; }
    }
}
