//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funtion_Group
    {
        public Funtion_Group()
        {
            this.Function_Page = new HashSet<Function_Page>();
        }
    
        public short Funtion_Group_Id { get; set; }
        public string Funtion_Group1 { get; set; }
        public Nullable<short> System_Id { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Aerc_System Aerc_System { get; set; }
        public virtual ICollection<Function_Page> Function_Page { get; set; }
    }
}
