//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land_Office
    {
        public Land_Office()
        {
            this.Town = new HashSet<Town>();
        }
    
        public short Land_Office_Id { get; set; }
        public string Land_Office_Code { get; set; }
        public string Land_Office1 { get; set; }
        public string City_Code { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Town> Town { get; set; }
    }
}
