//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land_Number
    {
        public int Land_Number_Id { get; set; }
        public string Land_Code { get; set; }
        public Nullable<int> Section_Id { get; set; }
        public Nullable<byte> Land_type_Id { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
    
        public virtual Land_Type Land_Type { get; set; }
        public virtual Section Section { get; set; }
    }
}
