//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soil_Type
    {
        public Soil_Type()
        {
            this.Soil = new HashSet<Soil>();
        }
    
        public short Soil_Type_Id { get; set; }
        public string Soil_Type1 { get; set; }
    
        public virtual ICollection<Soil> Soil { get; set; }
    }
}
