//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Town
    {
        public Town()
        {
            this.Section = new HashSet<Section>();
            this.Unit_Town = new HashSet<Unit_Town>();
        }
    
        public short Town_Id { get; set; }
        public string Town_Code { get; set; }
        public string Town1 { get; set; }
        public Nullable<short> Zip_Code { get; set; }
        public Nullable<short> Land_Office_Id { get; set; }
        public string City_Code { get; set; }
        public Nullable<int> Indigenous { get; set; }
    
        public virtual City City { get; set; }
        public virtual Land_Office Land_Office { get; set; }
        public virtual ICollection<Section> Section { get; set; }
        public virtual ICollection<Unit_Town> Unit_Town { get; set; }
    }
}
