//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.Organization = new HashSet<Organization>();
            this.Unit_Town = new HashSet<Unit_Town>();
            this.Unit11 = new HashSet<Unit>();
        }
    
        public short Unit_Id { get; set; }
        public string Unit1 { get; set; }
        public Nullable<short> Parent_Unit { get; set; }
    
        public virtual ICollection<Organization> Organization { get; set; }
        public virtual ICollection<Unit_Town> Unit_Town { get; set; }
        public virtual ICollection<Unit> Unit11 { get; set; }
        public virtual Unit Unit2 { get; set; }
    }
}
