//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public Case()
        {
            this.VerMapping = new HashSet<VerMapping>();
        }
    
        public int EventNo { get; set; }
        public System.Guid FId { get; set; }
        public byte ApplyYear { get; set; }
        public short ApplyUnit { get; set; }
        public int IANum { get; set; }
        public bool Gold { get; set; }
        public byte Step { get; set; }
        public bool Complete { get; set; }
        public System.Guid CId { get; set; }
        public System.DateTime CDate { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public bool Enable { get; set; }
        public bool Is12 { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string Reason { get; set; }
    
        public virtual Farmer Farmer { get; set; }
        public virtual ICollection<VerMapping> VerMapping { get; set; }
    }
}
