//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseDetail
    {
        public int EventNo { get; set; }
        public Nullable<int> MapNo { get; set; }
        public System.Guid FId { get; set; }
        public byte ApplyYear { get; set; }
        public short ApplyUnit { get; set; }
        public int IANum { get; set; }
        public bool Gold { get; set; }
        public string IdNo { get; set; }
        public string Name { get; set; }
        public string CityCode { get; set; }
        public string Addr { get; set; }
        public string Phone { get; set; }
        public string Tel { get; set; }
        public bool IsMember { get; set; }
        public byte Step { get; set; }
        public System.Guid DesId { get; set; }
        public string Designer_Name { get; set; }
        public bool Complete { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string EndTypeCNS { get; set; }
        public string FTpeCNS { get; set; }
        public string CatalogCNS { get; set; }
        public string landTown { get; set; }
        public string landCity { get; set; }
        public Nullable<double> buildarea { get; set; }
        public Nullable<double> farmarea { get; set; }
        public Nullable<double> finalarea { get; set; }
        public Nullable<int> Indigenous { get; set; }
    }
}
