//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasePayDetail
    {
        public int mapno { get; set; }
        public Nullable<int> 田間管路設施費 { get; set; }
        public Nullable<int> 規劃設計費 { get; set; }
        public Nullable<int> 水源設施費 { get; set; }
        public Nullable<int> 調控設施費 { get; set; }
        public Nullable<int> 動力設備費 { get; set; }
        public Nullable<int> 蓄水設備費 { get; set; }
        public Nullable<int> 設施費總計 { get; set; }
        public Nullable<int> 工作費 { get; set; }
        public Nullable<int> FarmerFee { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
