//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CntrlMat
    {
        public int MatNo { get; set; }
        public int CFNo { get; set; }
        public short CntrlCode { get; set; }
        public string MatName { get; set; }
        public short MatAmt { get; set; }
        public double MatPrice { get; set; }
        public short MatAmtAply { get; set; }
        public double MatPriceAply { get; set; }
    
        public virtual CntrlFac CntrlFac { get; set; }
    }
}
