//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DryEntities : DbContext
    {
        public DryEntities()
            : base("name=DryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CntrlApply> CntrlApply { get; set; }
        public DbSet<CntrlFac> CntrlFac { get; set; }
        public DbSet<CntrlList> CntrlList { get; set; }
        public DbSet<ControlLimit> ControlLimit { get; set; }
        public DbSet<DesignerList> DesignerList { get; set; }
        public DbSet<EFile> EFile { get; set; }
        public DbSet<EndTypeList> EndTypeList { get; set; }
        public DbSet<EngApply> EngApply { get; set; }
        public DbSet<Engine> Engine { get; set; }
        public DbSet<EngineList> EngineList { get; set; }
        public DbSet<EngLimit> EngLimit { get; set; }
        public DbSet<Examine> Examine { get; set; }
        public DbSet<FacDesign> FacDesign { get; set; }
        public DbSet<FacInspection> FacInspection { get; set; }
        public DbSet<FacStatList> FacStatList { get; set; }
        public DbSet<FacSysMAT> FacSysMAT { get; set; }
        public DbSet<FacTypeList> FacTypeList { get; set; }
        public DbSet<FacVerify> FacVerify { get; set; }
        public DbSet<Farm> Farm { get; set; }
        public DbSet<FarmChange> FarmChange { get; set; }
        public DbSet<FarmCrop> FarmCrop { get; set; }
        public DbSet<FarmDataLog> FarmDataLog { get; set; }
        public DbSet<Farmer> Farmer { get; set; }
        public DbSet<FarmerSys> FarmerSys { get; set; }
        public DbSet<FileTypeList> FileTypeList { get; set; }
        public DbSet<IrrWaterList> IrrWaterList { get; set; }
        public DbSet<LandTypeList> LandTypeList { get; set; }
        public DbSet<Mat_Module> Mat_Module { get; set; }
        public DbSet<MAT_Spec> MAT_Spec { get; set; }
        public DbSet<MAT_Types> MAT_Types { get; set; }
        public DbSet<MoneyRules> MoneyRules { get; set; }
        public DbSet<PigingLimit> PigingLimit { get; set; }
        public DbSet<Pool> Pool { get; set; }
        public DbSet<PoolApply> PoolApply { get; set; }
        public DbSet<PoolTonList> PoolTonList { get; set; }
        public DbSet<PoolTypeList> PoolTypeList { get; set; }
        public DbSet<PriceOfMat> PriceOfMat { get; set; }
        public DbSet<RegionList> RegionList { get; set; }
        public DbSet<StdFacSys> StdFacSys { get; set; }
        public DbSet<StdFacSysMAT> StdFacSysMAT { get; set; }
        public DbSet<Subsidy> Subsidy { get; set; }
        public DbSet<SubsidyItemList> SubsidyItemList { get; set; }
        public DbSet<VerifyLog> VerifyLog { get; set; }
        public DbSet<VerMapping> VerMapping { get; set; }
        public DbSet<WaterSrcList> WaterSrcList { get; set; }
        public DbSet<WrkExecutReport> WrkExecutReport { get; set; }
        public DbSet<Old_CountryCode> Old_CountryCode { get; set; }
        public DbSet<Old_Farm> Old_Farm { get; set; }
        public DbSet<Old_Farmer> Old_Farmer { get; set; }
        public DbSet<Old_Unit> Old_Unit { get; set; }
        public DbSet<LastVerOfMapNo> LastVerOfMapNo { get; set; }
        public DbSet<Pay> Pay { get; set; }
        public DbSet<EndType> EndType { get; set; }
        public DbSet<MatGroup> MatGroup { get; set; }
        public DbSet<PigingConf> PigingConf { get; set; }
        public DbSet<OldSystemFarm> OldSystemFarm { get; set; }
        public DbSet<LiugongReport> LiugongReport { get; set; }
        public DbSet<LiugongReport_Crop> LiugongReport_Crop { get; set; }
        public DbSet<LiugongReport_Engine> LiugongReport_Engine { get; set; }
        public DbSet<LiugongReport_Piging> LiugongReport_Piging { get; set; }
        public DbSet<LiugongReport_Pool> LiugongReport_Pool { get; set; }
        public DbSet<TotalFunds> TotalFunds { get; set; }
        public DbSet<FarmData> FarmData { get; set; }
        public DbSet<AcceptanceReportData> AcceptanceReportData { get; set; }
        public DbSet<CntrlMat> CntrlMat { get; set; }
        public DbSet<LiugongReport_Town> LiugongReport_Town { get; set; }
        public DbSet<TotalFee> TotalFee { get; set; }
        public DbSet<CasePayDetail> CasePayDetail { get; set; }
        public DbSet<FarmerSysM> FarmerSysM { get; set; }
        public DbSet<CropAreaDetail> CropAreaDetail { get; set; }
        public DbSet<LandEquity> LandEquity { get; set; }
        public DbSet<CasePayUnit> CasePayUnit { get; set; }
        public DbSet<UserLog> UserLog { get; set; }
        public DbSet<SummaryView> SummaryView { get; set; }
        public DbSet<Indigenous> Indigenous { get; set; }
        public DbSet<CaseDetail> CaseDetail { get; set; }
        public DbSet<FarmReapplyQuery> FarmReapplyQuery { get; set; }
        public DbSet<LandData> LandData { get; set; }
        public DbSet<LeisureFarm> LeisureFarm { get; set; }
        public DbSet<LeisureFarm_LandInfo> LeisureFarm_LandInfo { get; set; }
        public DbSet<SWCBPools> SWCBPools { get; set; }
        public DbSet<Case> Case { get; set; }
        public DbSet<SubsidyLimit> SubsidyLimit { get; set; }
    }
}
