//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFile
    {
        public int No { get; set; }
        public int MapNo { get; set; }
        public byte FileType { get; set; }
        public string Filepath { get; set; }
        public string Coordinate { get; set; }
        public string FileDes { get; set; }
        public System.DateTime UpldTime { get; set; }
        public bool Enable { get; set; }
    
        public virtual VerMapping VerMapping { get; set; }
    }
}
