//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndType
    {
        public int EndTypeID { get; set; }
        public int MapNo { get; set; }
        public byte EndTypeCode { get; set; }
        public byte FacType { get; set; }
        public string BranchPipeMat { get; set; }
        public Nullable<double> BranchPipeSpec { get; set; }
        public Nullable<double> StdpipeHei { get; set; }
        public string StdpipeMat { get; set; }
        public Nullable<double> StdpipeSpec { get; set; }
        public double SL { get; set; }
        public double SS { get; set; }
        public string SprinklerType { get; set; }
        public Nullable<double> SprinklerSpec { get; set; }
    
        public virtual EndTypeList EndTypeList { get; set; }
        public virtual FacTypeList FacTypeList { get; set; }
        public virtual PigingConf PigingConf { get; set; }
    }
}
