//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngineList
    {
        public EngineList()
        {
            this.Engine = new HashSet<Engine>();
            this.EngLimit = new HashSet<EngLimit>();
        }
    
        public byte EngCode { get; set; }
        public string EngCNS { get; set; }
    
        public virtual ICollection<Engine> Engine { get; set; }
        public virtual ICollection<EngLimit> EngLimit { get; set; }
    }
}
