//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examine
    {
        public int MapNo { get; set; }
        public string EnginePnt { get; set; }
        public string WaterPnt { get; set; }
        public byte Result { get; set; }
        public string Reason { get; set; }
        public System.Guid Examiner { get; set; }
        public System.DateTime EDate { get; set; }
        public string Note { get; set; }
    
        public virtual VerMapping VerMapping { get; set; }
    }
}
