//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacSysMAT
    {
        public FacSysMAT()
        {
            this.PriceOfMat = new HashSet<PriceOfMat>();
        }
    
        public int POMNo { get; set; }
        public int ModuleNo { get; set; }
        public short Bunit { get; set; }
        public string MName { get; set; }
        public Nullable<double> SpecLength { get; set; }
        public int MatType { get; set; }
        public string Spec { get; set; }
        public Nullable<int> SpecNo1 { get; set; }
        public Nullable<int> SpecNo2 { get; set; }
        public Nullable<int> SpecNo3 { get; set; }
        public string ItemUnit { get; set; }
        public string Note { get; set; }
    
        public virtual MAT_Spec MAT_Spec { get; set; }
        public virtual MAT_Types MAT_Types { get; set; }
        public virtual ICollection<PriceOfMat> PriceOfMat { get; set; }
    }
}
