//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacVerify
    {
        public int V_RecNo { get; set; }
        public byte StatCode { get; set; }
        public string VDes { get; set; }
        public System.DateTime VDate { get; set; }
        public System.Guid VId { get; set; }
        public int ReduceM { get; set; }
        public int PayM { get; set; }
    }
}
