//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm
    {
        public Farm()
        {
            this.FarmChange = new HashSet<FarmChange>();
            this.FarmCrop = new HashSet<FarmCrop>();
            this.LandEquity = new HashSet<LandEquity>();
        }
    
        public System.Guid FNo { get; set; }
        public int MapNo { get; set; }
        public int Section { get; set; }
        public string LandNo { get; set; }
        public byte LandType { get; set; }
        public string Long { get; set; }
        public string Lat { get; set; }
        public double FarmArea { get; set; }
        public double BuildArea { get; set; }
        public double FinalArea { get; set; }
        public Nullable<bool> IsApplied { get; set; }
        public string ApplicationStatus { get; set; }
        public Nullable<int> AppliedArea { get; set; }
        public Nullable<double> AreaCanApply { get; set; }
        public bool Outside { get; set; }
        public int Pcent_Chd { get; set; }
        public int Pcent_Par { get; set; }
    
        public virtual VerMapping VerMapping { get; set; }
        public virtual ICollection<FarmChange> FarmChange { get; set; }
        public virtual ICollection<FarmCrop> FarmCrop { get; set; }
        public virtual ICollection<LandEquity> LandEquity { get; set; }
    }
}
