//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer
    {
        public Farmer()
        {
            this.Case = new HashSet<Case>();
        }
    
        public System.Guid FId { get; set; }
        public string IdNo { get; set; }
        public string Name { get; set; }
        public string CityCode { get; set; }
        public string Addr { get; set; }
        public string Phone { get; set; }
        public string Tel { get; set; }
        public bool IsMember { get; set; }
        public System.Guid CId { get; set; }
        public System.DateTime CDate { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    
        public virtual ICollection<Case> Case { get; set; }
    }
}
