//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerSysM
    {
        public int No { get; set; }
        public string FarSysNo { get; set; }
        public int POMNo { get; set; }
        public Nullable<int> ModuleNo { get; set; }
        public string ModuleCNS { get; set; }
        public Nullable<int> MatGroupID { get; set; }
        public Nullable<int> MatOrder { get; set; }
        public string MatGroupCNS { get; set; }
        public string MName { get; set; }
        public string Spec { get; set; }
        public Nullable<double> Spec1 { get; set; }
        public string SpecName1 { get; set; }
        public Nullable<double> Spec2 { get; set; }
        public string SpecName2 { get; set; }
        public Nullable<double> Spec3 { get; set; }
        public string SpecName3 { get; set; }
        public string ItemUnit { get; set; }
        public double SysPrice { get; set; }
        public string Note { get; set; }
        public int Amount { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    
        public virtual FarmerSys FarmerSys { get; set; }
        public virtual MatGroup MatGroup { get; set; }
    }
}
