//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandData
    {
        public int Section_Id { get; set; }
        public string City { get; set; }
        public string Land_Office { get; set; }
        public string Land_Office_Code { get; set; }
        public string Town { get; set; }
        public Nullable<int> Section_Code { get; set; }
        public string Section { get; set; }
        public string Subsection { get; set; }
        public string LandCode { get; set; }
        public string TownCode { get; set; }
        public Nullable<int> Indigenous { get; set; }
    }
}
