//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeisureFarm
    {
        public LeisureFarm()
        {
            this.LeisureFarm_LandInfo = new HashSet<LeisureFarm_LandInfo>();
        }
    
        public int LicenseId { get; set; }
        public string Farm_name { get; set; }
        public string Site { get; set; }
        public string License_Exp { get; set; }
    
        public virtual ICollection<LeisureFarm_LandInfo> LeisureFarm_LandInfo { get; set; }
    }
}
