//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiugongReport_Crop
    {
        public int IANum { get; set; }
        public Nullable<int> MapNo { get; set; }
        public byte ApplyYear { get; set; }
        public short ApplyUnit { get; set; }
        public string Name { get; set; }
        public string Section { get; set; }
        public string LandNo { get; set; }
        public double FarmArea { get; set; }
        public double BuildArea { get; set; }
        public short CropCode { get; set; }
        public string Crop { get; set; }
    }
}
