//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiugongReport_Piging
    {
        public Nullable<int> MapNo { get; set; }
        public Nullable<byte> IrrWCode { get; set; }
        public Nullable<double> L1 { get; set; }
        public Nullable<double> L2 { get; set; }
        public Nullable<double> SL { get; set; }
        public Nullable<double> SS { get; set; }
        public Nullable<byte> FacType { get; set; }
        public string FTpeCNS { get; set; }
        public Nullable<byte> EndTypeCode { get; set; }
        public string MAT { get; set; }
        public string ItemUnit { get; set; }
        public string Note { get; set; }
        public short Amount { get; set; }
        public double SysPrice { get; set; }
        public double Total { get; set; }
        public Nullable<int> WorkPrice { get; set; }
    }
}
