//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Old_Farmer
    {
        public int id { get; set; }
        public string 年度 { get; set; }
        public string 單位 { get; set; }
        public string 編號1 { get; set; }
        public string 編號2 { get; set; }
        public string 鄉鎮 { get; set; }
        public string 地區分類 { get; set; }
        public string 推廣類別 { get; set; }
        public string 農作物 { get; set; }
        public string 農作物1 { get; set; }
        public string 農作物2 { get; set; }
        public string 農作物3 { get; set; }
        public string 農作物4 { get; set; }
        public string 灌溉型式 { get; set; }
        public string 動力 { get; set; }
        public string 動力1 { get; set; }
        public string 動力2 { get; set; }
        public string 動力3 { get; set; }
        public string 動力4 { get; set; }
        public string 動力5 { get; set; }
        public string 動力6 { get; set; }
        public string 抽水機 { get; set; }
        public Nullable<double> 蓄水池1 { get; set; }
        public Nullable<double> 蓄水池2 { get; set; }
        public Nullable<double> 蓄水池3 { get; set; }
        public string 水源設施 { get; set; }
        public string 水源管路類別 { get; set; }
        public Nullable<double> 設施面積 { get; set; }
        public string 身份証字號 { get; set; }
        public string 姓名 { get; set; }
        public string 電話 { get; set; }
        public string 地址1 { get; set; }
        public string 地址2 { get; set; }
        public string 勘查日期 { get; set; }
        public string 驗收日期 { get; set; }
        public string 設施情形 { get; set; }
        public Nullable<double> 末端設施費 { get; set; }
        public Nullable<double> 設計費 { get; set; }
        public Nullable<double> 審查費 { get; set; }
        public Nullable<double> 動力輔助款 { get; set; }
        public Nullable<double> 蓄水池輔助款 { get; set; }
        public Nullable<double> 水源管路設施費 { get; set; }
        public Nullable<double> 調控設施費 { get; set; }
        public Nullable<double> 水井設施費 { get; set; }
        public Nullable<double> 農戶配合款 { get; set; }
        public Nullable<double> 政府總輔助款 { get; set; }
        public Nullable<double> 水源設施輔助款 { get; set; }
        public Nullable<double> 調控設施輔助款 { get; set; }
        public string 備註 { get; set; }
        public Nullable<double> SS { get; set; }
        public Nullable<double> SL { get; set; }
        public string 系統設計代號 { get; set; }
        public string 灌溉器名稱 { get; set; }
        public string 蓄水池材質 { get; set; }
        public Nullable<bool> 重複 { get; set; }
        public string 更新日期 { get; set; }
        public Nullable<int> 抽水機數量 { get; set; }
        public Nullable<int> 蓄水池數量 { get; set; }
        public string 工作站代號 { get; set; }
        public string 行動電話 { get; set; }
        public string 設計人 { get; set; }
        public string 住址鄉鎮 { get; set; }
        public Nullable<bool> 灌區外 { get; set; }
    }
}
