//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldSystemFarm
    {
        public string 年度 { get; set; }
        public string 單位 { get; set; }
        public string 編號1 { get; set; }
        public string 編號2 { get; set; }
        public string 灌溉型式 { get; set; }
        public string CITY { get; set; }
        public string CITYCNS { get; set; }
        public string SECNO { get; set; }
        public string SEC { get; set; }
        public string SECCNS1 { get; set; }
        public string SECCNS2 { get; set; }
        public string 地目 { get; set; }
        public double 面積 { get; set; }
        public string 地號1 { get; set; }
        public string 地號2 { get; set; }
        public string 地號3 { get; set; }
        public string 備註 { get; set; }
        public bool 灌區外 { get; set; }
    }
}
