//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PigingLimit
    {
        public int ID { get; set; }
        public int LimitID { get; set; }
        public byte EndType { get; set; }
        public Nullable<byte> FacType { get; set; }
        public double SubsidyReference { get; set; }
        public int FacilityFee { get; set; }
        public int WorkingFee { get; set; }
    
        public virtual EndTypeList EndTypeList { get; set; }
        public virtual FacTypeList FacTypeList { get; set; }
        public virtual SubsidyLimit SubsidyLimit { get; set; }
    }
}
