//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PigingConf
    {
        public PigingConf()
        {
            this.EndType = new HashSet<EndType>();
            this.FarmerSys = new HashSet<FarmerSys>();
        }
    
        public int MapNo { get; set; }
        public double L1 { get; set; }
        public string L1Mat { get; set; }
        public Nullable<double> L1Spec { get; set; }
        public double L1Price { get; set; }
        public short L1Amount { get; set; }
        public double L2 { get; set; }
        public string L2Mat { get; set; }
        public Nullable<double> L2Spec { get; set; }
        public double L2Price { get; set; }
        public short L2Amount { get; set; }
        public string Cblock { get; set; }
        public byte IrrWCode { get; set; }
        public string OtherDescript { get; set; }
        public int WorkPrice { get; set; }
    
        public virtual ICollection<EndType> EndType { get; set; }
        public virtual ICollection<FarmerSys> FarmerSys { get; set; }
        public virtual VerMapping VerMapping { get; set; }
    }
}
