//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsidy
    {
        public short SNo { get; set; }
        public short SYear { get; set; }
        public short ApplyUnit { get; set; }
        public int Total_M { get; set; }
        public int Now_M { get; set; }
        public int FcstArea { get; set; }
        public int FcstAmt { get; set; }
        public Nullable<short> IAUnit { get; set; }
    }
}
