//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsidyLimit
    {
        public SubsidyLimit()
        {
            this.ControlLimit = new HashSet<ControlLimit>();
            this.EngLimit = new HashSet<EngLimit>();
            this.PigingLimit = new HashSet<PigingLimit>();
            this.PoolTonList = new HashSet<PoolTonList>();
        }
    
        public int LimitID { get; set; }
        public short ApplyYear { get; set; }
        public short ApplyUnit { get; set; }
        public double GeneralPercent { get; set; }
        public Nullable<double> GoldPercent { get; set; }
        public double MountainIncrease { get; set; }
        public int TotalLimit { get; set; }
        public int PersionLimit { get; set; }
        public int EngineMaxSubsidy { get; set; }
        public double ControlMinimumArea { get; set; }
        public int PoolMaxSubsidy { get; set; }
        public double PoolMinimumArea { get; set; }
        public int ControlMaxSubsidy { get; set; }
        public double AppliedPercent { get; set; }
        public double PlanningFee { get; set; }
    
        public virtual ICollection<ControlLimit> ControlLimit { get; set; }
        public virtual ICollection<EngLimit> EngLimit { get; set; }
        public virtual ICollection<PigingLimit> PigingLimit { get; set; }
        public virtual ICollection<PoolTonList> PoolTonList { get; set; }
    }
}
