//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerMapping
    {
        public VerMapping()
        {
            this.EFile = new HashSet<EFile>();
            this.Farm = new HashSet<Farm>();
            this.VerifyLog = new HashSet<VerifyLog>();
            this.Pay = new HashSet<Pay>();
        }
    
        public int MapNo { get; set; }
        public int EventNo { get; set; }
        public short ChgVer { get; set; }
        public string ChgReason { get; set; }
        public System.DateTime ChgDate { get; set; }
        public System.Guid ChgId { get; set; }
    
        public virtual CntrlApply CntrlApply { get; set; }
        public virtual ICollection<EFile> EFile { get; set; }
        public virtual EngApply EngApply { get; set; }
        public virtual Examine Examine { get; set; }
        public virtual FacDesign FacDesign { get; set; }
        public virtual FacInspection FacInspection { get; set; }
        public virtual ICollection<Farm> Farm { get; set; }
        public virtual PoolApply PoolApply { get; set; }
        public virtual ICollection<VerifyLog> VerifyLog { get; set; }
        public virtual ICollection<Pay> Pay { get; set; }
        public virtual PigingConf PigingConf { get; set; }
        public virtual TotalFee TotalFee { get; set; }
        public virtual Case Case { get; set; }
    }
}
