//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrkExecutReport
    {
        public short WNo { get; set; }
        public byte EYear { get; set; }
        public short ApplyUnit { get; set; }
        public double FcstArea { get; set; }
        public short FcstAmt { get; set; }
        public double CapitalAcc { get; set; }
        public double CurrentAcc { get; set; }
        public double M_Dis { get; set; }
        public double M_Used { get; set; }
        public short FinishAmt { get; set; }
        public short FinishArea { get; set; }
    }
}
